version: "3.8"  # Ensure the version is specified

services:
  backend:
    build:
      context: ./sports-app-backend  # Path to backend Dockerfile
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Expose port 5000 on the host to access the backend
    environment:
      - FLASK_ENV=development
    networks:
      - sports_network  # Use a custom network to connect frontend and backend

  frontend:
    build:
      context: ./frontend  # Path to frontend Dockerfile
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Expose frontend on port 5173
    environment:
      - VITE_BACKEND_URL=http://localhost:5000  # Backend URL within the Docker network
    networks:
      - sports_network  # Use the same network as backend

networks:
  sports_network:  # Define a custom network for the services to communicate
